server:
  port: 8081
  servlet:
    context-path: /resource-server

## STARTER: com.c4-soft.springaddons
origins: '*'
issuer: 'http://localhost:8180/auth/realms/my'

com:
  c4-soft:
    springaddons:
      security:
        cors:
          - path: /**
            allowed-origins: ${origins}
        issuers:
          - location: ${issuer}
            username-claim: preferred_username
            authorities:
              - path: $.realm_access.roles
                prefix: ROLE_
              - path: $.resource_access.*.roles
                prefix: ROLE_CLIENT_
              - path: $.scope
                prefix: SCOPE_

        permit-all:
          - "/actuator/health/readiness"
          - "/actuator/health/liveness"
          - "/v3/api-docs/**"
          - "/swagger-ui/**"
          - "/swagger-ui.html"

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8180/auth/realms/my'
          jwk-set-uri: 'http://localhost:8180/auth/realms/my/protocol/openid-connect/certs'

springdoc:
  swagger-ui:
    oauth:
      clientId: demoApp
      clientSecret: 0TxeKLnweDZYp9ZKBkSmKpYY1elgViQ3



####### KEYCLOAK
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: my   # tudo em minusculo


