server:
  port: 8081
  servlet:
    context-path: /resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8180/auth/realms/my'
          jwk-set-uri: 'http://localhost:8180/auth/realms/my/protocol/openid-connect/certs'

springdoc:
  swagger-ui:
    oauth:
      clientId: demoApp
      clientSecret: 0TxeKLnweDZYp9ZKBkSmKpYY1elgViQ3

####### KEYCLOAK
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: my   # tudo em minusculo


